/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;

/**
 *
 * @author Ricardo
 */
public class VentanaReporte extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReporte
     */
    public VentanaReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMes = new javax.swing.JComboBox<>();
        botonObtener = new javax.swing.JButton();
        labelMejorVendedor = new javax.swing.JLabel();
        labelTotalVentas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelMejorVenta = new javax.swing.JLabel();
        labelVendedor = new javax.swing.JLabel();
        labelPromedioVentas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonImprimir = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Ventas");

        jcMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        botonObtener.setText("Obtener");

        labelMejorVendedor.setText("Mejor Vendedor:");

        labelTotalVentas.setText("Total Ventas:");

        labelMejorVenta.setText("Mejor Venta:");

        labelVendedor.setText("Vendedor:");

        labelPromedioVentas.setText("Promedio Ventas:");

        botonImprimir.setText("Imprimir");
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMejorVendedor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonObtener)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPromedioVentas)
                            .addComponent(labelVendedor)
                            .addComponent(labelMejorVenta)
                            .addComponent(labelTotalVentas)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(botonImprimir)
                .addGap(57, 57, 57)
                .addComponent(botonCerrar)
                .addGap(0, 111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonObtener))
                .addGap(18, 18, 18)
                .addComponent(labelMejorVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMejorVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVendedor)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPromedioVentas)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonImprimir)
                    .addComponent(botonCerrar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_botonCerrarActionPerformed

    public JButton getBotonCerrar() {
        return botonCerrar;
    }

    public void setBotonCerrar(JButton botonCerrar) {
        this.botonCerrar = botonCerrar;
    }

    public JButton getBotonImprimir() {
        return botonImprimir;
    }

    public void setBotonImprimir(JButton botonImprimir) {
        this.botonImprimir = botonImprimir;
    }

    public JButton getBotonObtener() {
        return botonObtener;
    }

    public void setBotonObtener(JButton botonObtener) {
        this.botonObtener = botonObtener;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JComboBox<String> getJcMes() {
        return jcMes;
    }

    public void setJcMes(JComboBox<String> jcMes) {
        this.jcMes = jcMes;
    }

    public JLabel getLabelMejorVendedor() {
        return labelMejorVendedor;
    }

    public void setLabelMejorVendedor(JLabel labelMejorVendedor) {
        this.labelMejorVendedor = labelMejorVendedor;
    }

    public JLabel getLabelMejorVenta() {
        return labelMejorVenta;
    }

    public void setLabelMejorVenta(JLabel labelMejorVenta) {
        this.labelMejorVenta = labelMejorVenta;
    }

    public JLabel getLabelPromedioVentas() {
        return labelPromedioVentas;
    }

    public void setLabelPromedioVentas(JLabel labelPromedioVentas) {
        this.labelPromedioVentas = labelPromedioVentas;
    }

    public JLabel getLabelTotalVentas() {
        return labelTotalVentas;
    }

    public void setLabelTotalVentas(JLabel labelTotalVentas) {
        this.labelTotalVentas = labelTotalVentas;
    }

    public JLabel getLabelVendedor() {
        return labelVendedor;
    }

    public void setLabelVendedor(JLabel labelVendedor) {
        this.labelVendedor = labelVendedor;
    }

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        JOptionPane.showMessageDialog(null, "Reporte de ventas impreso exitosamente");
    }//GEN-LAST:event_botonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonObtener;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcMes;
    private javax.swing.JLabel labelMejorVendedor;
    private javax.swing.JLabel labelMejorVenta;
    private javax.swing.JLabel labelPromedioVentas;
    private javax.swing.JLabel labelTotalVentas;
    private javax.swing.JLabel labelVendedor;
    // End of variables declaration//GEN-END:variables
}
